# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d48e39581b2b623f747babd1fe0ffcc4"
application_url = "https://example.com"
embedded = true
name = "shipping-cost-optimizer"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_shipping,read_locations,read_inventory,read_products"

[webhooks]
api_version = "2027-01"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
